<?php
if (! defined ( 'sugarEntry' ) || ! sugarEntry)
	die ( 'Not A Valid Entry Point' );

require_once ('include/MVC/View/views/view.list.php');
class Customosy_services_companiesViewList extends ViewList {

    public function preDisplay()
    {
        parent::preDisplay();
        include ('custom/modules/osy_services_companies/osy_includejs.php');
        $this->lv->actionsMenuExtraItems[] = $this->buildMyMenuItem();
    }

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
        echo "<script type='text/javascript' src='custom/include/osy_utils.js'></script>";
    }

    protected function buildMyMenuItem()
    {
        global $app_strings;

        return <<<EOHTML
<a href="javascript:void(0)" onclick="return osy_send_form(true, 'osy_services_companies', 'index.php?entryPoint=osy_exportOppServCompanies&module=osy_services_companies','Please select at least 1 record to proceed.')" style="text-align:center;margin-top:5px;margin-bottom:5px;width: 230px" class="menuItem">Export Services for individual companies</a>
EOHTML;
    }


    /*public function Display() {
        parent::Display ();
        include ('custom/modules/osy_services_companies/osy_includejs.php');
        $this->lv->targetList = true;
    }*/

	/*function listViewProcess() {
		global $mod_strings,$app_strings;
		require_once("custom/include/osyFileEdit.php");
		$this->processSearchForm();
		$this->lv->searchColumns = $this->searchForm->searchColumns;

		//OPENSYMBOLMOD paolo.santacatterina (09/gen/2015  15:38:07)
		//AITCILO-26 problema ricerca avanzata
		//************************************************************
		if(!$this->headers)
			return;
		//************************************************************

		$sDivStart = "<div style='float:left'>";
		$sDivEnd = "</div>";

		$sModuleName = $this->seed->module_dir;


			<script type='text/javascript' src='custom/include/osy_utils.js'></script>

/*
		$sButtonExportServiceCompanies=$sDivStart.'<a href="javascript:void(0)" onclick="return osy_send_form(true, \''.$sModuleName.'\', \'index.php?entryPoint=osy_exportOppServCompanies&module='.$sModuleName.'\',\''.$app_strings['LBL_LISTVIEW_NO_SELECTED'].'\')"';
// 		$sButtonExportServiceCompanies=$sDivStart.'<a onclick="window.open(\'index.php?module='.$sModuleName.'&amp;action=exportServiceCompanies&amp;to_pdf=1\',\'\',\'width=800,height=650\');"';
		$sButtonExportServiceCompanies .= 'style="text-align:center;margin-top:5px;margin-bottom:5px;width: 230px" class=\'menuItem\' href=\'#\'>'.$mod_strings['LBL_OSY_EXPORT_SERVICE_COMP'].'</a>'.$sDivEnd;
		$a1CodeHooks=array(
				array
				(
						'orig'=>'/(selectedObjectsSpan[^<]+\<\/td\>)/m',
						'new'=>'$1<td nowrap="nowrap" width=\'2%\' class=\'paginationActionButtons\'>'.$sButtonExportServiceCompanies.'</td>',
				)
		);
		$s1FilePath=file_edit("include/ListView/ListViewPagination.tpl",$a1CodeHooks,"",$sModuleName);

		$a2CodeHooks=array(
				array
				(
						'orig'=>'/\{include file\=\'include\/ListView\/ListViewPagination\.tpl\'\}/',
						'new'=>'{include file=\''.$s1FilePath.'\'}',
				)
		);

		$s2FilePath=file_edit("include/ListView/ListViewGeneric.tpl",$a2CodeHooks,"",$sModuleName);

		$this->lv->setup($this->seed, $s2FilePath, $this->where, $this->params);

		echo $this->lv->display();
	}*/
}
