<?php

$dictionary['osy_service_users'] = array(
		'table' => 'osy_service_users',
		'fields' => array(
				array(	'name'			=> 'id',
						'type'			=> 'varchar',
						'len'			=> '36',
				),
				array(	'name'			=> 'osy_service_id',
						'type'			=> 'varchar',
						'len'			=> '36',
				),
				array(	'name'			=> 'user_id',
						'type'			=> 'varchar',
						'len'			=> '36',
				),
				array(	'name'			=> 'required',
						'type'			=> 'varchar',
						'len'			=> '1',
						'default'		=> '1',
				),
				array(	'name'			=> 'accept_status',
						'type'			=> 'varchar',
						'len'			=> '25',
						'default'		=> 'none',
				),
				array(	'name'			=> 'date_modified',
						'type'			=> 'datetime',
				),
				array(	'name'			=> 'deleted',
						'type'			=> 'bool',
						'len'			=> '1',
						'default'		=> '0',
						'required'		=> false,
				),
		),
		'indices' => array(
				array(	'name'			=> 'osy_service_userspk',
						'type'			=> 'primary',
						'fields'		=> array('id'),
				),
				array(	'name'			=> 'idx_usr_osy_service',
						'type'			=> 'index',
						'fields'		=> array('osy_service_id'),
				),
				array(	'name'			=> 'idx_usr_osy_service_usr',
						'type'			=> 'index',
						'fields'		=> array('user_id'),
				),
				array(	'name'			=> 'idx_osy_service_users',
						'type'			=> 'alternate_key',
						'fields'		=> array('osy_service_id', 'user_id'),
				),
		),
		'relationships' => array(
				'osy_service_users' => array(
						'lhs_module'		=> 'osy_service',
						'lhs_table'			=> 'osy_service',
						'lhs_key'			=> 'id',
						'rhs_module'		=> 'Users',
						'rhs_table'			=> 'users',
						'rhs_key'			=> 'id',
						'relationship_type'	=> 'many-to-many',
						'join_table'		=> 'osy_service_users',
						'join_key_lhs'		=> 'osy_service_id',
						'join_key_rhs'		=> 'user_id',
				),
		),
);