<?php
if (!defined('sugarEntry') || !sugarEntry)
    die ('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

require_once('include/MVC/View/views/view.list.php');
require_once('modules/Opportunities/OpportunitiesListViewSmarty.php');

class CustomOpportunitiesViewList extends ViewList
{
    function CustomOpportunitiesViewList()
    {
        parent::ViewList();
    }

    public function preDisplay()
    {
        parent::preDisplay();
        include ('custom/modules/osy_services_companies/osy_includejs.php');
        $this->lv->actionsMenuExtraItems[] = $this->buildMyMenuItem();
    }

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
        echo "<script type='text/javascript' src='custom/include/osy_utils.js'></script>";
    }

    protected function buildMyMenuItem()
    {
        global $app_strings;

        return <<<EOHTML
<a href="javascript:void(0)" onclick="return osy_send_form(true, 'Opportunities', 'index.php?entryPoint=osy_exportOppServCompanies&amp;module=Opportunities','Please select at least 1 record to proceed.')" style="text-align:center;margin-top:5px;margin-bottom:5px;width: 150px" class="menuItem">Export Subscription Fees</a>
EOHTML;
    }

    /*function preDisplay()
    {
        $this->lv = new OpportunitiesListViewSmarty();
    }

    function listViewProcess()
    {
        global $mod_strings, $app_strings;
        require_once("custom/include/osyFileEdit.php");
        $this->processSearchForm();
        $this->lv->searchColumns = $this->searchForm->searchColumns;

        //OPENSYMBOLMOD paolo.santacatterina (09/gen/2015  15:38:07)
        //AITCILO-26 problema ricerca avanzata
        //************************************************************
        if (!$this->headers)
            return;
        //************************************************************

        $sDivStart = "<div style='float:left'>";
        $sDivEnd = "</div>";

        $sModuleName = $this->seed->module_dir;

        */
        /*<script type='text/javascript' src='custom/include/osy_utils.js'></script>*/

/*
        $sButtonExportSubscriptionFees = $sDivStart . '<a href="javascript:void(0)" onclick="return osy_send_form(true, \'' . $sModuleName . '\', \'index.php?entryPoint=osy_exportOppServCompanies&module=' . $sModuleName . '\',\'' . $app_strings['LBL_LISTVIEW_NO_SELECTED'] . '\')"';
// 		$sButtonExportSubscriptionFees=$sDivStart.'<a onclick="window.open(\'index.php?module='.$sModuleName.'&amp;action=exportSubscriptionFees&amp;to_pdf=1\',\'\',\'width=800,height=650\');"';
        $sButtonExportSubscriptionFees .= 'style="text-align:center;margin-top:5px;margin-bottom:5px;width: 150px" class=\'menuItem\' href=\'#\'>' . $mod_strings['LBL_OSY_EXPORT_SUBSCRIPTION_FEES'] . '</a>' . $sDivEnd;

        $a1CodeHooks = array(
            array
            (
                'orig' => '/(selectedObjectsSpan[^<]+\<\/td\>)/m',
                'new' => '$1<td nowrap="nowrap" width=\'2%\' class=\'paginationActionButtons\'>' . $sButtonExportSubscriptionFees . '</td>',
            )
        );
        $s1FilePath = file_edit("include/ListView/ListViewPagination.tpl", $a1CodeHooks, "", $sModuleName);

        $a2CodeHooks = array(
            array
            (
                'orig' => '/\{include file\=\'include\/ListView\/ListViewPagination\.tpl\'\}/',
                'new' => '{include file=\'' . $s1FilePath . '\'}',
            )
        );

        $s2FilePath = file_edit("include/ListView/ListViewGeneric.tpl", $a2CodeHooks, "", $sModuleName);

        $this->lv->setup($this->seed, $s2FilePath, $this->where, $this->params);

        echo $this->lv->display();
    }*/
}

?>